def correct_currency_name(currency_name):
    """
    Takes different forms for currency names (like code, or abbreviation), outputs a
    standardized name. This function is to make sure that all the names for the
    crypto currencies are the same.
    """
    currency_name = currency_name.rstrip()
    correct_name_mapping_dict = {
        'BURSTCoin': 'Burst',
        'Ether': 'Ethereum',
        'OmiseGo': 'OmiseGO',
        'Tron': 'TRON',
        'ZCash': 'Zcash',
        'Zencash': 'ZenCash',

        'CAD': 'Canadian Dollar',
        'EUR': 'Euro',
        'GBP': 'British Pound',
        'JPY': 'Japanese Yen',
        'U.S. dollar': 'US Dollar',
        "USD": "US Dollar",

        'ADA': 'Cardano',
        'AE': 'Aeternity',
        'AION': 'Aion',
        'ARDR': 'Ardor',
        'ARK': 'Ark',
        'AMP': 'Synereo',
        'BAT': 'Basic Attention Token',
        'BCD': 'Bitcoin Diamond',
        'BCH': 'Bitcoin Cash',
        'BCN': 'Bytecoin',
        'BIX': 'Bibox Token',
        'BURST': 'Burst',
        'BNB': 'Binance Coin',
        'BNT': 'Bancor',
        'BTC': 'Bitcoin',
        'BTCP': 'Bitcoin Private',
        'BTG': 'Bitcoin Gold',
        'BTM': 'Bytom',
        'BTS': 'BitShares',
        'CMT': 'CyberMiles',
        'CNX': 'Cryptonex',
        'CTXC': 'Cortex',
        'DASH': 'Dash',
        'DAO': 'The DAO',
        'DCN': 'Dentacoin',
        'DCR': 'Decred',
        'DDD': 'Scry.info',
        'DGB': 'DigiByte',
        'DGD': 'DigixDAO',
        'DOGE': 'Dogecoin',
        'DRGN': 'Dragonchain',
        'DROP': 'Dropil',
        'ELA': 'Elastos',
        'ELF': 'aelf',
        'EMC': 'Emercoin',
        'ENG': 'Enigma',
        'EOS': 'EOS',
        'ETC': 'Ethereum Classic',
        'ETH': 'Ethereum',
        'ETHOS': 'Ethos',
        'ETN': 'Electroneum',
        'FSN': 'Fusion',
        'FUN': 'FunFair',
        'GAS': 'Gas',
        'GBG': 'Golos Gold',
        'GNT': 'Golem',
        "GNO": "Gnosis",
        'GOLOS': 'Golos',
        'GXS': 'GXChain',
        'HSR': 'Hshare',
        'HT': 'Huobi Token',
        'ICN': 'Iconomi',
        'ICX': 'ICON',
        'IOST': 'IOST',
        'KCS': 'KuCoin Shares',
        'KIN': 'Kin',
        'KMD': 'Komodo',
        'KNC': 'Kyber Network',
        'LOOM': 'Loom Network',
        'LRC': 'Loopring',
        'LSK': 'Lisk',
        'LTC': 'Litecoin',
        'MAID': 'MaidSafeCoin',
        'MANA': 'Decentraland',
        'MIOTA': 'IOTA',
        'MITH': 'Mithril',
        'MLN': 'Melon ',
        'MKR': 'Maker',
        'MOAC': 'MOAC',
        'MONA': 'MonaCoin',
        'NANO': 'Nano',
        'NAS': 'Nebulas',
        'NEO': 'NEO',
        'NMC': 'Namecoin',
        'NULS': 'Nuls',
        'NXT': 'Nxt',
        'OMG': 'OmiseGO',
        'ONT': 'Ontology',
        'OMNI': 'Omni',
        'PIVX': 'PIVX',
        'POLY': 'Polymath',
        'PPT': 'Populous',
        'QASH': 'QASH',
        'QTUM': 'Qtum',
        'RDD': 'ReddCoin',
        'REP': 'Augur',
        'RHOC': 'RChain',
        'SC': 'Siacoin',
        'SNT': 'Status',
        'STEEM': 'Steem',
        'STORJ': 'Storj',
        'STRAT': 'Stratis',
        'SUB': 'Substratum',
        'SYS': 'Syscoin',
        'THETA': 'Theta Token',
        'TRX': 'TRON',
        'USDT': 'Tether',
        'VEN': 'VeChain',
        'VERI': 'Veritaseum',
        'WAN': 'Wanchain',
        'WAVES': 'Waves',
        'WICC': 'WaykiChain',
        'WTC': 'Waltonchain',
        'XBT': 'Bitcoin',
        'XDG': 'Dogecoin',
        'XEM': 'NEM',
        'XLM': 'Stellar',
        'XMR': 'Monero',
        'XRP': 'Ripple',
        'XVG': 'Verge',
        'ZEC': 'Zcash',
        'ZEN': 'ZenCash',
        'ZIL': 'Zilliqa',
        'ZRX': '0x',
    }
    for code, name in correct_name_mapping_dict.items():
        if currency_name == code:
            currency_name = name
    return currency_name
