# Generated by Django 2.0.5 on 2018-06-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('url', models.CharField(max_length=255)),
                ('example', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('C', 'Crypto'), ('F', 'Fiat')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.URLField()),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=30, max_digits=60)),
                ('ask', models.DecimalField(decimal_places=30, max_digits=60)),
                ('unix_timestamp', models.PositiveIntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_set', to='exchange_rate.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Exchange')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_set', to='exchange_rate.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Currency'),
        ),
        migrations.AddField(
            model_name='code',
            name='exchange',
            field=models.ManyToManyField(to='exchange_rate.Exchange'),
        ),
        migrations.AddField(
            model_name='apimethod',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Exchange'),
        ),
    ]
