# Generated by Django 2.0.5 on 2018-05-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('C', 'Crypto'), ('F', 'Fiat')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=30, max_digits=60)),
                ('ask', models.DecimalField(decimal_places=30, max_digits=60)),
                ('datetime', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_set', to='exchange_rate.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Exchange')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_set', to='exchange_rate.Currency')),
            ],
        ),
    ]
