# Generated by Django 2.0.5 on 2018-06-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairApiName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='TradablePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_names', models.ManyToManyField(to='exchange_rate.PairApiName')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradablepair_base_set', to='exchange_rate.Currency')),
                ('exchanges', models.ManyToManyField(to='exchange_rate.Exchange')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradablepair_quote_set', to='exchange_rate.Currency')),
            ],
        ),
    ]
