# Generated by Django 2.0.5 on 2018-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='api_url',
            field=models.URLField(default='https://www.bitstamp.net/api/v2/'),
            preserve_default=False,
        ),
    ]
