# Generated by Django 2.0.5 on 2018-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0002_pairapiname_tradablepair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairapiname',
            name='exchange',
        ),
        migrations.AddField(
            model_name='pairapiname',
            name='exchanges',
            field=models.ManyToManyField(to='exchange_rate.Exchange'),
        ),
    ]
