# Generated by Django 2.0.5 on 2018-06-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0002_exchange_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.Currency'),
        ),
        migrations.AddField(
            model_name='code',
            name='exchange',
            field=models.ManyToManyField(to='exchange_rate.Exchange'),
        ),
    ]
